# Use an official Node runtime as a parent image
FROM node:16

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Install any needed packages specified in package.json
# RUN npm install

# Make port 41234 available to the world outside this container
EXPOSE 41234

# Run receiver.js when the container launches
CMD ["node", "receiver.js"]

# ! docker build -t gitm-receiver -f Dockerfile.receiver .
# ! docker run --network gitm-network --name gitm-receiver-ctnr gitm-receiver
